### PR TITLE
Dependency Injection-related API enhancements

### PR DESCRIPTION
**Pull request by robertmclaws**
## Purpose
This PR addresses changes discussed in [this WebApi thread](https://github.com/OData/WebApi/issues/2442). The goal is ultimately to enable OData injected services that are consistent between APIs to be shared in a single container, and have a mechanism to first resolve services from a route-specific DI container, falling back to the shared container if the service was not resolved.

There will also be cosmetic changes to attempt to make references more intuitive & consistent between different parts of the API surface.

There will be lots of changes, so I will attempt to make each check-in atomic so they will be easier to individually review.

#### ODataOptions changes, Part 1:
- Rename Models to RouteComponents to better align with how it is used internally
- Name the Tuples on RouteComponents to improve discoverability
- Add a method to enable all DefaultQueryOptions in one fell swoop
- Rename BuildContainBuilder to BuildRouteContainer.
- Extensive documentation enhancements

All tests except public API diffs pass.

### CODE REVIEW

**Comment by xuzhg** [comment]
@robertmclaws Is this PR still in Draft status?

**Comment by xuzhg** [comment]
@robertmclaws I just rebased the PR to the latest master. I will continue on the changes.

**Comment by xuzhg** [comment]
@robertmclaws I retrieved your changes for the options setting and merged them at 6ba8af77b100d735291dce32bd41f98fe00e2380.

For the DI refactor, it seems we need more time to make it completed. (Make the refactor ok, let all test case pass).

I am thinking maybe we can postpone DI refactor in the 8.1 release?

**Comment by xuzhg** [comment]
@robertmclaws Can we move it on?

**Comment by robertmclaws** [comment]
I'm going to have to re-base and take a look at it again. Probably won't be able to until the weekend though.

**Comment by xuzhg** [comment]
@robertmclaws any chance to continue this? I'd have a new release sooner.

**Pull request closed without merging**
