### PR TITLE
ODL 7.16.0 makes ASP OData build hang-on

### PR DESCRIPTION
**Pull request by xuzhg**
Let's update to ODL 7.17.0

### CODE REVIEW

**Review by KenitoInc — APPROVED** [review]

**Review by gathogojr — APPROVED** [review]
:shipit:

**Comment by mikepizzo** [comment]
@xuzhg  -- Do we know what about ODL 7.16 makes the ASP OData build hang? Is there a debug assert raised by ODL, or an issue that an app would encounter calling the release ODL 7.16?

**Review by mikepizzo — COMMENTED** [review]
@xuzhg -- Do we know what about ODL 7.16 makes the ASP OData build hang? Is there a debug assert raised by ODL, or an issue that an app would encounter calling the release ODL 7.16?

**Comment by xuzhg** [comment]
> @xuzhg -- Do we know what about ODL 7.16 makes the ASP OData build hang? Is there a debug assert raised by ODL, or an issue that an app would encounter calling the release ODL 7.16?

@mikepizzo , thanks for reviewing.
I assumed it could be related to ODL commits and Checked with @ElizabethOkerio, it could be related to:

https://github.com/OData/odata.net/pull/2670
https://github.com/OData/odata.net/pull/2671

However, the build is still hang on. I will continue to follow up it.

**Comment by xuzhg** [comment]
It seems it is related to https://github.com/OData/AspNetCoreOData/pull/1013

The root cause is:
In an asysc test case, we can an async method using sync pattern. It's blocking the test running.

**Pull request closed without merging**
