### PR TITLE
Stable ordering should be applied when using the EDM model for paging (in addition to EnableQueryAttribute.PageSize)

### PR DESCRIPTION
**Pull request by dmitry-chistyakov**
We use server-side paging feature and encountered an issue where OData applies stable ordering to the output dataset for $skip, $top, and EnableQueryAttribute.PageSize.

However, OData overlooks scenarios in which paging is defined through the EDM model, even though stable ordering logic should also be applied in such cases.

Although EnableQueryAttribute.PageSize is useful, it can become unwieldy in specific situations, especially when it propagates throughout all internal collections. This can lead to unexpected navigation through internal structures and retrieval of missing data. Additionally, issues may arise when constructing the @odata.nextLink for contained collections.

### CODE REVIEW

**Comment by dmitry-chistyakov** [comment]
@microsoft-github-policy-service agree company="Intermedia"

**Comment by ElizabethOkerio** [comment]
@dmitry-chistyakov please add tets

**Comment by gathogojr** [comment]
Thank you @dmitry-chistyakov for your contribution. Could you please add tests to validate your change?

**Comment by dmitry-chistyakov** [comment]
> Thank you @dmitry-chistyakov for your contribution. Could you please add tests to validate your change?

Done. Please check.

**Comment by dmitry-chistyakov** [comment]
> @dmitry-chistyakov please add tests

Done. Please check.

**Review by gathogojr — APPROVED** [review]
:shipit:

**Review by KenitoInc — APPROVED** [review]

**Comment by gathogojr** [comment]
Thank you @dmitry-chistyakov for your contribution

**Pull request merged**
