### PR TITLE
Verify the compute clause in compute query validator

### PR DESCRIPTION
**Pull request by xuzhg**
issue #730. 

Update the Compute query validator to let ODL verify the compute clause.

### CODE REVIEW

**Comment by xuzhg** [comment]
> 

@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by xuzhg** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by xuzhg** [comment]
@dnperfors Please take a look.

**Review by dnperfors — APPROVED** [review]
LGTM

**Pull request merged**
