### PR TITLE
Async query enumeration and cancellation support for long running queries

### PR DESCRIPTION
**Pull request by henning-krause**
A long time ago I created an [issue](https://github.com/OData/WebApi/issues/1788) to properly cancel long running queries (when the HttpContext.RequestAborted cancellation token is triggered) for the 7.9 version of this code. This was never solved, I think mainly because most of the code is still synchronous.

Now that I moved on to AspNetCoreOData I'm facing the same problem and gave it another shot.

@xuzhg I know that this PR is far from complete. But I wanted to get an opinion from you if I'm moving in the right direction with this and if you would approve this PR once it's complete before I put more effort in this.

For now, I have mainly redesigned the TruncatedCollection to properly support async enumeration (and remove the buffering of the whole response along with this change) as well as the ODataResourceSetSerializer.

So, for paged queries, this approach works.

### CODE REVIEW

**Comment by henning-krause** [comment]
@corranrogue9 I've resolved all the comments you had.

**Comment by corranrogue9** [comment]
> @corranrogue9 I've resolved all the comments you had.

Thanks, I've approved

**Comment by henning-krause** [comment]
@xuzhg All unit tests are green and @corranrogue9 approved the changes.

**Comment by henning-krause** [comment]
@xuzhg Is there anything I need to do to get this PR into a state where it can be merged?

**Pull request closed without merging**
