### PR TITLE
Revert the changes for duplicated left JOIN changes.

### LINKED ISSUE #1044: Revert the changes for https://github.com/OData/AspNetCoreOData/pull/993
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**
The changes in 'https://github.com/OData/AspNetCoreOData/pull/993' introduces the regression. 

See details at:  https://github.com/OData/AspNetCoreOData/issues/1035

Before fixing the issue without regression, let's revert the changes.

### PR DESCRIPTION
**Pull request by xuzhg**
fixes #1044

1) revert the changes for duplicated left JOIN changes. 
2) Add the regression tests. 
3) Update the version to 8.2.3

Revert the changes:
https://github.com/OData/AspNetCoreOData/pull/993
https://github.com/OData/AspNetCoreOData/pull/1024
https://github.com/OData/AspNetCoreOData/pull/1031

### CODE REVIEW

**Review by ElizabethOkerio — APPROVED** [review]

**Comment by gathogojr** [comment]
@xuzhg Does this pull request also revert changes introduced by other pull requests that were merged in the attempt to fix the regression:
- https://github.com/OData/AspNetCoreOData/pull/1024
- https://github.com/OData/AspNetCoreOData/pull/1031

**Comment by xuzhg** [comment]
> @xuzhg Does this pull request also revert changes introduced by other pull requests that were merged in the attempt to fix the regression:
> 
> * [#1023 - Fix all structural properties ignored when using `$expand` without `$select` and camel cased property names #1024](https://github.com/OData/AspNetCoreOData/pull/1024)
> * [fix binding readonly properties #1031](https://github.com/OData/AspNetCoreOData/pull/1031)

Oh, Yes.

**Comment by xuzhg** [comment]
@gathogojr Do you have other concerns?

**Comment by gathogojr** [comment]
> @gathogojr Do you have other concerns?

No @xuzhg

**Review by gathogojr — APPROVED** [review]

**Pull request merged**
