### PR TITLE
Custom implemention for JSON Serialization of AggregationWrapper

### PR DESCRIPTION
**Pull request by adrua**
Custom implemention for JSON Serialization of AggregationWrapper

for resolve error

"The converter specified on 'Microsoft.AspNetCore.OData.Query.Wrapper.GroupByWrapper' is not compatible with the type 'Microsoft.AspNetCore.OData.Query.Wrapper.GroupByWrapper"

During Json Serialization of Query Result

resolve issue: https://github.com/OData/WebApi/issues/2015

### CODE REVIEW

**Comment by adrua** [comment]
signed as submitted

**Comment by SenyaMur** [comment]
When it will be merge and publish?

**Comment by cilerler** [comment]
@xuzhg, can you look into this, please? If this will resolve OData/WebApi#2015 we can start using ODATA with the latest and greatest version of DOTNET

Thanks in advance 🤗

**Comment by xuzhg** [comment]
I can include this into the Preview-3

---
In reply to: [740252334](https://github.com/OData/AspNetCoreOData/pull/39#issuecomment-740252334) [](ancestors = 740252334)

**Comment by xuzhg** [comment]
It's implemented yet. Thanks

**Pull request closed without merging**
