### PR TITLE
Update alternate key sample to support core alternatekey term

### PR DESCRIPTION
**Pull request by xuzhg**
Update alternate key sample to support core alternatekey term.

### CODE REVIEW

**Comment by xuzhg** [comment]
@julealgon

**Comment by gathogojr** [comment]
Maybe you should change `core_c_r` to `core_c_or_r` so it's easy to relate to the existing `c_or_r` (CountryOrRegion)

**Comment by gathogojr** [comment]
Maybe you should change `CoreSN` to `CoreSSN` so it's easy to relate it to the existing `SSN`

**Comment by xuzhg** [comment]
@gathogojr Thanks for your suggestion. Actually, I attentionally named them as it. What I thought is that it can be 'any' qualified alias. Is it ok for you?

**Comment by gathogojr** [comment]
> @gathogojr Thanks for your suggestion. Actually, I attentionally named them as it. What I thought is that it can be 'any' qualified alias. Is it ok for you?

If it was intentional and not inadvertent that's okay...

**Review by gathogojr — APPROVED** [review]
:shipit:

**Review by Nthemba — APPROVED** [review]

**Pull request merged**
